
                                                 #USERS

//REGISTER A USER
POST  http://localhost:4000/user/register
Content-Type: application/json

{
    "name":"Jill",
    "email":"jill@gmail.com",
    "password":"kevin123"

}


// USER LOGIN
###
POST  http://localhost:4000/user/login
Content-Type: application/json

{
   
   "email":"jill@gmail.com",
    "password":"kevin123"
}

### UPDATE USER
PUT http://localhost:4000/users/update/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI0ODY1ZTY2Ny05ODRjLTRiYzgtYWI5Yi0wNTI0MmExMWNiN2MiLCJuYW1lIjoia2lsbCIsImVtYWlsIjoia2lsbEBnbWFpbC5jb20iLCJjcmVhdGVkX2F0IjoiMjAyMy0wMy0yNFQwMDowMDowMC4wMDBaIiwiaXNfc2VudCI6ZmFsc2UsInJvbGUiOmZhbHNlLCJpc19kZWxldGVkIjpmYWxzZSwiaWF0IjoxNjc5NjI3Njc5LCJleHAiOjE2Nzk3MTQwNzl9.r8A-_aByxQyq98ZO4x72cuICMFsCRfzuLwnvcn-fSbY
Content-Type: application/json

{
   
}


//GET USER BY ID
###
GET http://localhost:4000/user/98922034-54b1-4b16-a919-65e89e48a97f


### DELETE USER

DELETE   http://localhost:4000/user/delete/39e6d17f-78a9-46d7-9ff7-7fc468ee6c2b
 

### GET ALL USERS
GET http://localhost:4000/user/all/ll



                                                          #QUESTIONS

### CREATE A QUESTION
POST http://localhost:4000/question/create
Content-Type: application/json

{
  "question": "PEP VS TENHAG",
  "description": "Which needs the other"
  

}


### UPDATE QUESTION
PUT http://localhost:4000/question/update/b2182e4b-5ebd-48d3-a9ab-f84b6acf222e
Content-Type: application/json

{
  "question": " JAVSCRIPT AND HTML?",
  "body": "Which needs the other",
  "userid":"39e6d17f-78a9-46d7-9ff7-7fc468ee6c2b",
  "views": 1

}

### 
# GET QUESTION BY ID
GET http://localhost:4000/question/b2182e4b-5ebd-48d3-a9ab-f84b6acf222e



### 
# GET ALL QUESTIONS
GET http://localhost:4000/question/all



### DELETE QUESTION
DELETE  http://localhost:4000/questions/delete/b2182e4b-5ebd-48d3-a9ab-f84b6acf222e




                                //QUESTION VOTES

### CREATE QUESTION VOTE
POST http://localhost:4000/questionvote/createvote
Content-Type: application/json

{
  "vote": 1,
   "userid":"39e6d17f-78a9-46d7-9ff7-7fc468ee6c2b",
  "questionid":"b2182e4b-5ebd-48d3-a9ab-f84b6acf222e"
  
  
}

### UPDATE QUESTION VOTE
PUT http://localhost:4000/questionvote/update/id
Content-Type: application/json

{
  "questionid":"Q001",
  "userid":"U001",
  "vote": -1
  
}

### GET ALL QUESTION VOTES
GET http://localhost:4000/questionvote/getall


### GET QUESTION VOTE BY ID
GET http://localhost:4000/questionvote/getvote/c1acebec-3504-4e0e-9153-d4076c2c60e9






  


                                       //ANSWERS

### GET ALL ANSWERS
GET http://localhost:4000/answer/allanswers



### GET ANSWER BY ID
GET http://localhost:4000/answer/f0e6d909-3750-4a90-9bef-cea17b39ea37

### CREATE ANSWER
POST http://localhost:4000/answer/createanswer
Content-Type: application/json

{
  "answer": "Javascript needs css but css dosent need javascript",
  "questionid":"b2182e4b-5ebd-48d3-a9ab-f84b6acf222e",
  "userid":"39e6d17f-78a9-46d7-9ff7-7fc468ee6c2b",
  "is_accepted": "0"


}

### UPDATE ANSWER
PUT http://localhost:400/answer/update/f0e6d909-3750-4a90-9bef-cea17b39ea37
Content-Type: application/json

{
{
  "answer": "Javascript needs css but css dosent need javascript",
  "userid":"39e6d17f-78a9-46d7-9ff7-7fc468ee6c2b",
  "questionid":"b2182e4b-5ebd-48d3-a9ab-f84b6acf222e",
  "is_accepted": "1"

}

}


### DELETE ANSWER
DELETE http://localhost:4000/answer/delete/f0e6d909-3750-4a90-9bef-cea17b39ea37





                                         //ANSWER VOTES


### CREATE ANSWER VOTE
POST http://localhost:4000/answervote/create
Content-Type: application/json

{
   "vote": -1,
   "userid":"39e6d17f-78a9-46d7-9ff7-7fc468ee6c2b",
  "answerid":"34752876-c68f-4927-8df5-57479d70cd73"
  
  
}
### UPDATE ANSWER VOTE
PUT http://localhost:4000/answervote/update/id
Content-Type: application/json
{
  "userid":"U002",
  "answerid":"ANS1",
  "vote": -1
}
  
###GET ANSWER VOTE BY ID
GET http://localhost:4000/answervote/id


### GET ALL ANSWER VOTES
GET http://localhost:4000/answervote/getall



                       

                       
                                             // TAGS

    
### CREATE TAG
POST http://localhost:4000/tag/createtag
Content-Type: application/json

{
  "tag":"CSS"
}


### UPDATE TAG
PUT http://localhost:4000/tag/update/40f5caa6-1976-4a90-a016-ca239e79a77c
Content-Type: application/json

{

}


### GET TAG BY ID
GET http://localhost:4000/tag/40f5caa6-1976-4a90-a016-ca239e79a77c

### GET ALL TAGS
GET http://localhost:4000/tag/getall


### DELETE TAG
DELETE http://localhost:4000/tag/delete/40f5caa6-1976-4a90-a016-ca239e79a77c




                                           //COMMENTS

### CREATE COMMENT
POST http://localhost:4000/comment/create
Content-Type: application/json

{
   "comment": "Good Answer",
 "userid":"39e6d17f-78a9-46d7-9ff7-7fc468ee6c2b",
  "answerid":"34752876-c68f-4927-8df5-57479d70cd73"
  
}


### UPDATE COMMENT

PUT http://localhost:4000/comment/update/"UP01"
Content-Type: application/json

{
  "comment": "Good Answer",
  "userid":"U002",
  "answerid":"ANS1",
  "is_deleted": "1"

}

###
GET http://localhost:4000/comment/67d08556-6953-4fa2-a6d7-92e438c27c00

### GET ALL COMMENT
GET http://localhost:4000/comment/getall


### DELETE COMMENT
DELETE http://localhost:4000/comment/delete/67d08556-6953-4fa2-a6d7-92e438c27c00





